[tox]
isolated_build=true
envlist =
	py{310,311}-pandas20-numpy1
	py{310,311}-pandas21-numpy1
	py{310,311,312,313}-pandas22-numpy{2}
	py{310,311,312,313}-pandas23-numpy{2}
	py{311,312,313,314}-pandas30-numpy{2}
skipdist = true

[testenv]
deps =
	matplotlib
	pytz
	typing-extensions
	pytest
	pytest-cov
	pandas20: pandas>=2.0,<2.1
	pandas21: pandas>=2.1,<2.2
	pandas22: pandas>=2.2,<2.3
	pandas23: pandas>=2.3,<3
	pandas30: pandas>=3.0,<3.1
	numpy1: numpy>=1,<2
    numpy2: numpy>=2,<3
skip_install = true
commands =
    pytest tests/
